
const reviewsData = [
    {img: 'user1.png', name: 'Din Johnson', text:'I have been using Solidi 3 for my business for several months now. It is an excellent payment system with fast transactions and an easy-to-use interface. Everything works smoothly, and support is always available. Highly recommended!', mark: 5, PaymentMethod: "MasterCard", data: 'March 23, 2023'},
    {img: 'user2.png', name: 'John Carter', text:'I am very satisfied with Solidi 3. All transactions are quick, and the interface is very intuitive. I have not encountered any issues so far. It is a great system for regular payments!', mark: 5, PaymentMethod: "Visa", data: 'December 1, 2024'},
    {img: 'user3.png', name: 'Dean Carrager', text:'Solidi 3 is exactly what I need to streamline my financial transactions. Payments are processed instantly, and I feel secure using it. I would definitely recommend this system to anyone who values time and security.', mark: 5, PaymentMethod: "MasterCard", data: 'April 09, 2024'},
    {img: 'user4.png', name: 'Margot Robbie', text:'Overall, it is a good service. It works reliably, but sometimes there are slight delays in transfers. If this issue gets resolved, I would give it 5 stars. Otherwise, everything is great.', mark: 4, PaymentMethod: "Visa", data: 'September 29, 2024'},
    {img: 'user5.png', name: 'Robert Black', text:'Solidi 3 is a fantastic payment system that has made my transactions effortless. The user interface is sleek, and I love how fast the transactions are. I have never had any issues. Highly recommend it!', mark: 5, PaymentMethod: "PayPal", data: 'July 14, 2024'},
    {img: 'user6.png', name: 'Emily Stone', text:'I’ve been using Solidi 3 for some time now, and it’s great for managing personal and business payments. The platform is secure and straightforward. The occasional minor delay is the only downside, but overall, it’s excellent.', mark: 4, PaymentMethod: "MasterCard", data: 'January 12, 2023'},
    {img: 'user7.png', name: 'Sophia White', text:'Using Solidi 3 has been an amazing experience. The payment system is quick, reliable, and very secure. I’ve recommended it to all my colleagues. Definitely a must-try for anyone looking for efficiency!', mark: 5, PaymentMethod: "Visa", data: 'May 3, 2024'},
    {img: 'user8.png', name: 'Pamela Green', text:'Solidi 3 is very user-friendly, and the speed of transactions is impressive. I use it daily for my business, and it has never let me down. Great service and excellent support team.', mark: 5, PaymentMethod: "Apple Pay", data: 'October 8, 2024'},
    {img: 'user9.png', name: 'Olivia Brown', text:'I like Solidi 3 because it’s very intuitive and handles payments securely. It’s a bit pricey compared to other options, but the reliability and speed make up for it. Worth every penny.', mark: 5, PaymentMethod: "PayPal", data: 'November 2, 2023'},
    
]

export default reviewsData